deploy_to_osd:
  image: quay.io/openshift/origin-cli:4.13
  stage: deploy  

  variables:
    HELM_TIMEOUT: "10m"
    OS_PROJECT: "mohamed-esmael-dev"
    OS_ADMIN_PROJECT: "mohamed-esmael-dev"

  before_script:
    - curl -fsSL https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz -o helm.tgz
    - tar -xzf helm.tgz && mv linux-amd64/helm /usr/local/bin/helm && chmod +x /usr/local/bin/helm
    - helm version

  script:
 
    - set -euo pipefail
    - echo "Logging into OpenShift..."
    - oc login --token="$OC_TOKEN" --server="$OC_SERVER" --insecure-skip-tls-verify=true

    - NAMESPACE_USER="${OS_PROJECT:-mohamed-esmael-dev}"
    - NAMESPACE_ADMIN="${OS_ADMIN_PROJECT:-mohamed-esmael-dev}"

    - oc project "$NAMESPACE_USER"  || true
    - oc project "$NAMESPACE_ADMIN" || true

    - echo "=== Creating GCP secret ==="
    - |
        if [ -n "${GCP_SA_KEY:-}" ]; then
          echo "Creating/updating OpenShift secret 'service-account.json' from CI var GCP_SA_KEY..."
          TMPFILE="$(mktemp /tmp/gcp-sa.XXXXXX)"
          if echo "$GCP_SA_KEY" | base64 --decode > "$TMPFILE" 2>/dev/null; then
            echo "GCP_SA_KEY decoded from base64 (hidden)."
          else
            echo "GCP_SA_KEY appears not base64; writing raw content to temp file."
            echo "$GCP_SA_KEY" > "$TMPFILE"
          fi
          # quick JSON validation (if python present)
          if command -v python3 >/dev/null 2>&1; then
            if ! python3 -c "import json,sys; json.load(open('$TMPFILE'))" 2>/dev/null; then
              echo "ERROR: service-account JSON is invalid"; rm -f "$TMPFILE"; exit 1
            fi
          elif command -v python >/dev/null 2>&1; then
            if ! python -c "import json,sys; json.load(open('$TMPFILE'))" 2>/dev/null; then
              echo "ERROR: service-account JSON is invalid"; rm -f "$TMPFILE"; exit 1
            fi
          fi
          oc delete secret service-account.json -n "$NAMESPACE_USER" --ignore-not-found || true
          oc create secret generic service-account.json -n "$NAMESPACE_USER" --from-file=service-account.json="$TMPFILE"
          oc delete secret service-account.json -n "$NAMESPACE_ADMIN" --ignore-not-found || true
          oc create secret generic service-account.json -n "$NAMESPACE_ADMIN" --from-file=service-account.json="$TMPFILE"
          shred -u "$TMPFILE" 2>/dev/null || rm -f "$TMPFILE"
        else
          echo "GCP_SA_KEY not provided — skipping service-account secret creation."
        fi

  
    - |
      # Compute CHUNK_IMAGE_FULL if not supplied (derived from artifact registry and IMAGE_TAG)
      if [ -z "${CHUNK_IMAGE_FULL:-}" ] && [ -n "${ARTIFACT_REG_HOST:-}" ] && [ -n "${PROJECT_ID:-}" ] && [ -n "${REPO:-}" ] && [ -n "${IMAGE_TAG:-}" ]; then
          CHUNK_IMAGE_FULL="${ARTIFACT_REG_HOST}/${PROJECT_ID}/${REPO}/chunk-image:${IMAGE_TAG}"
      fi

      split_repo_tag() {
        full="$1"
        repo="${full%%:*}"
        tag="${full#*:}"

        if [ "$repo" = "$tag" ]; then
          tag="latest"
        fi

        printf "%s|%s" "$repo" "$tag"
      }

    - echo "=== Resolving image names ==="
    - USER_BACKEND_IMAGE="${USER_BACKEND_IMAGE:-${ARTIFACT_REG_HOST}/${PROJECT_ID}/${REPO}/user-backend:${IMAGE_TAG}}"
    - USER_FRONTEND_IMAGE="${USER_FRONTEND_IMAGE:-${ARTIFACT_REG_HOST}/${PROJECT_ID}/${REPO}/user-frontend:${IMAGE_TAG}}"
    - ADMIN_BACKEND_IMAGE="${ADMIN_BACKEND_IMAGE:-${ARTIFACT_REG_HOST}/${PROJECT_ID}/${REPO}/admin-backend:${IMAGE_TAG}}"
    - ADMIN_FRONTEND_IMAGE="${ADMIN_FRONTEND_IMAGE:-${ARTIFACT_REG_HOST}/${PROJECT_ID}/${REPO}/admin-frontend:${IMAGE_TAG}}"
    - CHUNK_IMAGE="${CHUNK_IMAGE:-${CHUNK_IMAGE_FULL:-}}"

    - IFS='|' read -r USER_BACKEND_REPO USER_BACKEND_TAG <<< "$(split_repo_tag "$USER_BACKEND_IMAGE")"
    - IFS='|' read -r USER_FRONTEND_REPO USER_FRONTEND_TAG <<< "$(split_repo_tag "$USER_FRONTEND_IMAGE")"
    - IFS='|' read -r ADMIN_BACKEND_REPO ADMIN_BACKEND_TAG <<< "$(split_repo_tag "$ADMIN_BACKEND_IMAGE")"
    - IFS='|' read -r ADMIN_FRONTEND_REPO ADMIN_FRONTEND_TAG <<< "$(split_repo_tag "$ADMIN_FRONTEND_IMAGE")"

    - |
      if [ -n "$CHUNK_IMAGE" ]; then
        IFS='|' read -r CHUNK_REPO CHUNK_TAG <<< "$(split_repo_tag "$CHUNK_IMAGE")"
      fi

    - echo "Resolved images:"
    - echo " USER_BACKEND   = $USER_BACKEND_REPO:$USER_BACKEND_TAG"
    - echo " USER_FRONTEND  = $USER_FRONTEND_REPO:$USER_FRONTEND_TAG"
    - echo " ADMIN_BACKEND  = $ADMIN_BACKEND_REPO:$ADMIN_BACKEND_TAG"
    - echo " ADMIN_FRONTEND = $ADMIN_FRONTEND_REPO:$ADMIN_FRONTEND_TAG"
    - |
      if [ -n "$CHUNK_IMAGE" ]; then
        echo " CHUNK_IMAGE = $CHUNK_REPO:$CHUNK_TAG"
      fi

    - echo "=== Deploying USER Backend ==="
    - |
      helm upgrade --install esmael-user-backend ./helm/user_backend \
        --namespace "$NAMESPACE_USER" \
        --create-namespace \
        --wait --timeout "$HELM_TIMEOUT" \
        --set image.repository="$USER_BACKEND_REPO" \
        --set image.tag="$USER_BACKEND_TAG" \
        --set env.EMBEDDING_ENDPOINT="$EMBEDDING_ENDPOINT" \
        --set env.CHUNK_URL="$CHUNK_URL" \
        --set env.VECTOR_DB_ENDPOINT="$VECTOR_DB_ENDPOINT" \
        --set env.VECTOR_DB_ENDPOINT_UPSERT="$VECTOR_DB_ENDPOINT_UPSERT" \
        --set env.DEPLOYED_INDEX_ID="$DEPLOYED_INDEX_ID" \
        --set env.PROJECT_ID="$PROJECT_ID" \
        --set env.REGION="$REGION" \
        --set env.MEMORY_STORE_HOST="${MEMORY_STORE_HOST:-redis}" \
        --set env.MEMORY_STORE_PORT="${MEMORY_STORE_PORT:-6379}" \
        --set env.LLM_ENDPOINT="$LLM_ENDPOINT" \
        --set env.LLM_MODEL_ID="$LLM_MODEL_ID" \
        --set env.GOOGLE_APPLICATION_CREDENTIALS="/app/keys/service-account.json" \
        --set gcpServiceAccount.secretName="service-account.json" \
        --set gcpServiceAccount.mountPath="/app/keys" \
        --set gcpServiceAccount.fileName="service-account.json"



    - echo "=== Deploying USER Frontend ==="
    - |
      helm upgrade --install esmael-user-frontend ./helm/user_frontend \
        --namespace "$NAMESPACE_USER" \
        --create-namespace \
        --wait --timeout "$HELM_TIMEOUT" \
        --set image.repository="$USER_FRONTEND_REPO" \
        --set image.tag="$USER_FRONTEND_TAG" \
        --set env.VITE_API_URL="/api" 


    - echo "=== Deploying ADMIN Backend ==="
    - |
      helm upgrade --install esmael-admin-backend ./helm/admin_backend \
        --namespace "$NAMESPACE_ADMIN" \
        --create-namespace \
        --wait --timeout "$HELM_TIMEOUT" \
        --set image.repository="$ADMIN_BACKEND_REPO" \
        --set image.tag="$ADMIN_BACKEND_TAG" \
        --set env.CHUNK_URL="${CHUNK_URL}" \
        --set env.EMBEDDING_ENDPOINT="${EMBEDDING_ENDPOINT}" \
        --set env.VECTOR_DB_ENDPOINT="${VECTOR_DB_ENDPOINT}" \
        --set env.VECTOR_DB_ENDPOINT_UPSERT="${VECTOR_DB_ENDPOINT_UPSERT}" \
        --set env.DEPLOYED_INDEX_ID="${DEPLOYED_INDEX_ID}" \
        --set env.PROJECT_ID="${PROJECT_ID}" \
        --set env.REGION="${REGION}" \
        --set env.MEMORY_STORE_HOST="${MEMORY_STORE_HOST:-redis}" \
        --set env.MEMORY_STORE_PORT="${MEMORY_STORE_PORT:-6379}" \
        --set env.LLM_ENDPOINT="${LLM_ENDPOINT}" \
        --set env.LLM_MODEL_ID="${LLM_MODEL_ID}" \
        --set env.GOOGLE_APPLICATION_CREDENTIALS="/app/keys/service-account.json" \
        --set env.SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
        --set env.SUBSCRIPTION_PATH="$SUBSCRIPTION_PATH" \
        --set gcpServiceAccount.secretName="service-account.json" \
        --set gcpServiceAccount.mountPath="/app/keys" \
        --set gcpServiceAccount.fileName="service-account.json"


    - echo "=== Deploying ADMIN Frontend ==="
    - |
      helm upgrade --install esmael-admin-frontend ./helm/admin_frontend \
        --namespace "$NAMESPACE_ADMIN" \
        --create-namespace \
        --wait --timeout "$HELM_TIMEOUT" \
        --set image.repository="$ADMIN_FRONTEND_REPO" \
        --set image.tag="$ADMIN_FRONTEND_TAG" \
        --set env.VITE_API_URL="/api" 


  environment:
    name: osd/sandbox

  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

    - when: never
