substitutions:
  _ARTIFACT_REG_HOST: "${_ARTIFACT_REG_HOST}"
  _REPO: "${_REPO}"
  _PROJECT_ID: "${_PROJECT_ID}"
  _REGION: "${_REGION}"
  _GITLAB_PROJ_ID: "${_GITLAB_PROJ_ID}"
  _GITLAB_REF: "${_GITLAB_REF}"

logsBucket: gs://${_PROJECT_ID}-build-logs

availableSecrets:
  secretManager:
    - versionName: "projects/${_PROJECT_ID}/secrets/SONAR_TOKEN/versions/latest"
      env: "SONAR_TOKEN"
    - versionName: "projects/${_PROJECT_ID}/secrets/GITLAB/versions/latest"
      env: "GITLAB"

steps:
- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-fs-admin-backend'
  entrypoint: 'sh'
  args:
    - -c
    - |
      set -eux
      DIR=Admin_Backend
      if [ -d "${DIR}" ]; then
        echo "Trivy filesystem scan for ${DIR} (skipping .git,target)"
        trivy fs --exit-code 1 --severity HIGH,CRITICAL --skip-dirs .git,target "${DIR}" || { echo "Trivy fs scan failed"; exit 1; }
      else
        echo "No ${DIR}, skip"
      fi

- name: 'python:3.11'
  id: 'python-test-admin-backend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=Admin_Backend
      if [ -d "${DIR}" ]; then
        cd "${DIR}"
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "requirements.txt may be empty"
        pip install pytest || true
        if ls tests >/dev/null 2>&1 || grep -R "pytest" -q . ; then
          pytest -q || { echo "Unit tests failed"; exit 0; }
        else
          echo "No tests detected; skipping pytest"
        fi
      else
        echo "No ${DIR}, skip"
      fi

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build-admin-backend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=Admin_Backend
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:latest
      if [ -d "${DIR}" ]; then
        docker build -t "${IMAGE}" -t "${LATEST}" "${DIR}"
        docker save "${IMAGE}" -o /workspace/admin-backend.tar
      else
        echo "No ${DIR}, skip docker build"
      fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-image-admin-backend'
  entrypoint: 'sh'
  args:
    - -c
    - |
      set -eux
      TAR=/workspace/admin-backend.tar
      if [ -f "${TAR}" ]; then
        echo "Scanning ${TAR}..."
        trivy image --input "${TAR}" --exit-code 1 --severity HIGH,CRITICAL || { echo "Trivy image scan FAILED"; exit 0; }
      else
        echo "No tar, skip"
      fi

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push-admin-backend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:latest
      if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "${IMAGE}"; then
        docker push "${IMAGE}"
        docker push "${LATEST}"
      else
        echo "Image ${IMAGE} not found, skip push"
      fi

# ---------------- User_Backend (Python) ----------------
- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-fs-user-backend'
  entrypoint: 'sh'
  args: ['-c','set -eux; DIR=User_Backend; [ -d "${DIR}" ] && trivy fs --exit-code 1 --severity HIGH,CRITICAL --skip-dirs .git,target "${DIR}" || echo "skip"']

- name: 'python:3.11'
  id: 'python-test-user-backend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=User_Backend
      if [ -d "${DIR}" ]; then
        cd "${DIR}"
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install pytest || true
        if ls tests >/dev/null 2>&1 || grep -R "pytest" -q . ; then pytest -q; else echo "No tests found, skip"; fi
      else
        echo "skip"
      fi

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build-user-backend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=User_Backend
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:latest
      if [ -d "${DIR}" ]; then docker build -t "${IMAGE}" -t "${LATEST}" "${DIR}"; docker save "${IMAGE}" -o /workspace/user-backend.tar; else echo "skip"; fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-image-user-backend'
  entrypoint: 'sh'
  args: ['-c','set -eux; TAR=/workspace/user-backend.tar; [ -f "${TAR}" ] && trivy image --input "${TAR}" --exit-code 1 --severity HIGH,CRITICAL || echo "skip"']

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push-user-backend'
  entrypoint: 'bash'
  args: ['-c','set -eux; IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:${SHORT_SHA}; LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:latest; if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "${IMAGE}"; then docker push "${IMAGE}"; docker push "${LATEST}"; fi']

# ---------------- Chunk_Function (Python) ----------------
- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-fs-chunk'
  entrypoint: 'sh'
  args: ['-c','set -eux; DIR=Chunk_Function; [ -d "${DIR}" ] && trivy fs --exit-code 1 --severity HIGH,CRITICAL --skip-dirs .git,target "${DIR}" || echo "skip"']

- name: 'python:3.11'
  id: 'python-test-chunk'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=Chunk_Function
      if [ -d "${DIR}" ]; then
        cd "${DIR}"
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install pytest || true
        if ls tests >/dev/null 2>&1 || grep -R "pytest" -q . ; then pytest -q; else echo "No tests found, skip"; fi
      else
        echo "skip"
      fi

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build-chunk'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=Chunk_Function
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:latest
      if [ -d "${DIR}" ]; then docker build -t "${IMAGE}" -t "${LATEST}" "${DIR}"; docker save "${IMAGE}" -o /workspace/chunk-image.tar; else echo "skip"; fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-image-chunk'
  entrypoint: 'sh'
  args: ['-c','set -eux; TAR=/workspace/chunk-image.tar; [ -f "${TAR}" ] && trivy image --input "${TAR}" --exit-code 1 --severity HIGH,CRITICAL || echo "skip"']

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push-chunk'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:latest
      if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "${IMAGE}"; then docker push "${IMAGE}"; docker push "${LATEST}"; fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-fs-admin-frontend'
  entrypoint: 'sh'
  args: ['-c','set -eux; DIR=Admin_Frontend; [ -d "${DIR}" ] && trivy fs --exit-code 1 --severity HIGH,CRITICAL --skip-dirs .git,target "${DIR}" || echo "skip"']

- name: 'node:18'
  id: 'node-build-admin-frontend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=Admin_Frontend
      if [ -d "${DIR}" ]; then
        cd "${DIR}"
        if [ -f package.json ]; then
          npm ci
          if npm test --silent; then echo "Frontend tests passed"; else echo "Tests failed"; exit 0; fi
          if npm run build --silent; then echo "Build succeeded"; else echo "Build failed"; exit 0; fi
        else
          echo "No package.json, skip node steps"
        fi
      fi

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build-admin-frontend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=Admin_Frontend
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:latest
      if [ -d "${DIR}" ]; then docker build -t "${IMAGE}" -t "${LATEST}" "${DIR}"; docker save "${IMAGE}" -o /workspace/admin-frontend.tar; else echo "skip"; fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-image-admin-frontend'
  entrypoint: 'sh'
  args: ['-c','set -eux; TAR=/workspace/admin-frontend.tar; [ -f "${TAR}" ] && trivy image --input "${TAR}" --exit-code 1 --severity HIGH,CRITICAL || echo "skip"']

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push-admin-frontend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:latest
      if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "${IMAGE}"; then docker push "${IMAGE}"; docker push "${LATEST}"; fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-fs-user-frontend'
  entrypoint: 'sh'
  args: ['-c','set -eux; DIR=User_Frontend; [ -d "${DIR}" ] && trivy fs --exit-code 1 --severity HIGH,CRITICAL --skip-dirs .git,target "${DIR}" || echo "skip"']

- name: 'node:18'
  id: 'node-build-user-frontend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=User_Frontend
      if [ -d "${DIR}" ] && [ -f "${DIR}/package.json" ]; then
        cd "${DIR}"
        npm ci
        npm test || { echo "Frontend tests failed"; exit 0; }
        npm run build || { echo "Build failed"; exit 0; }
      else
        echo "skip"
      fi

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build-user-frontend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      DIR=User_Frontend
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:latest
      if [ -d "${DIR}" ]; then docker build -t "${IMAGE}" -t "${LATEST}" "${DIR}"; docker save "${IMAGE}" -o /workspace/user-frontend.tar; else echo "skip"; fi

- name: 'aquasec/trivy:0.45.1'
  id: 'trivy-image-user-frontend'
  entrypoint: 'sh'
  args: ['-c','set -eux; TAR=/workspace/user-frontend.tar; [ -f "${TAR}" ] && trivy image --input "${TAR}" --exit-code 1 --severity HIGH,CRITICAL || echo "skip"']

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-push-user-frontend'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      IMAGE=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:${SHORT_SHA}
      LATEST=${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:latest
      if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "${IMAGE}"; then docker push "${IMAGE}"; docker push "${LATEST}"; fi


- name: 'sonarsource/sonar-scanner-cli:latest'
  id: 'sonar-scan-all'
  secretEnv: ['SONAR_TOKEN']
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -eux
      # modules/folders to scan
      MODULES="Admin_Backend,User_Backend,Chunk_Function,Admin_Frontend,User_Frontend"
      PROJECT_KEY="HybridRAG_End-to-End_AI_Chatbot_on_OpenShift_OpenStack_GCP"   
      ORG="mohamedesmael10"             # change if different

      echo "Running SonarCloud scan for: ${MODULES}"
      # Run sonar scanner from repo root and tell sonar which folders to analyze:
      sonar-scanner \
        -Dsonar.projectKey="${PROJECT_KEY}" \
        -Dsonar.organization="${ORG}" \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.token"${SONAR_TOKEN}" \
        -Dsonar.sources="${MODULES}" \
        -Dsonar.coverage.exclusions="**/node_modules/**,**/venv/**" \
        -Dsonar.exclusions="**/target/**,**/*.tar,**/*.zip"

      echo "Sonar scan submitted. Polling quality gate..."
      # Poll SonarCloud quality gate (6 attempts x 10s = 60s)
      for i in $(seq 1 6); do
        sleep 10
        REPORT=$(curl -s -u "${SONAR_TOKEN}": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${PROJECT_KEY}")
        STATUS=$(echo "${REPORT}" | jq -r '.projectStatus.status // "PENDING"')
        echo "Sonar quality gate status: ${STATUS}"
        if [ "${STATUS}" = "OK" ]; then
          echo "Quality gate passed"
          break
        fi
        if [ "${STATUS}" = "ERROR" ] || [ "${STATUS}" = "WARN" ] || [ "${STATUS}" = "FAILED" ]; then
          echo "Quality gate FAILED: ${STATUS}"
          exit 0
        fi
        if [ "${i}" -eq 6 ]; then
          echo "Quality gate timed out; failing the build"
          exit 0
        fi
      done


- name: 'hashicorp/terraform:1.6.0'
  id: 'terraform-deploy'
  entrypoint: 'sh'
  args:
    - -c
    - |
      set -eux
      echo "=== Starting Terraform Deployment ==="
      echo "PROJECT_ID=${_PROJECT_ID} REGION=${_REGION}"
      cd Terraform/terraform-infra || { echo "Terraform dir missing"; exit 1; }
      terraform version
      terraform init -input=false -no-color -upgrade
      terraform validate -no-color
      terraform plan -input=false -no-color -lock=false \
        -var="project_id=${_PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="artifact_registry_host=${_ARTIFACT_REG_HOST}" \
        -var="repo=${_REPO}" \
        -var="chunk_image_tag=${SHORT_SHA}" \
        -out=tfplan
      terraform apply -auto-approve -no-color tfplan
      terraform output -json > /workspace/tf_outputs.json
      echo "Wrote /workspace/tf_outputs.json"

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: 'notify-gitlab'
  entrypoint: 'bash'
  secretEnv: ['GITLAB']
  args:
    - -c
    - |
      set -eux
      TF_JSON_FILE="/workspace/tf_outputs.json"
      if [ ! -f "${TF_JSON_FILE}" ]; then echo "ERROR: Terraform outputs not found"; exit 1; fi
      TF_JSON=$(cat "${TF_JSON_FILE}")
      EMBEDDING_ENDPOINT=$(echo "${TF_JSON}" | jq -r '.embedding_endpoint.value // empty')
      CHUNK_URL=$(echo "${TF_JSON}" | jq -r '.chunk_url.value // empty')
      VECTOR_DB_ENDPOINT=$(echo "${TF_JSON}" | jq -r '.vector_db_endpoint_find_neighbors.value // empty')
      VECTOR_DB_ENDPOINT_UPSERT=$(echo "${TF_JSON}" | jq -r '.vector_db_endpoint_upsert.value // empty')
      DEPLOYED_INDEX_ID=$(echo "${TF_JSON}" | jq -r '.deployed_index_id.value // empty')
      TF_PROJECT_ID=$(echo "${TF_JSON}" | jq -r '.project_id.value // empty')
      TF_REGION=$(echo "${TF_JSON}" | jq -r '.region.value // empty')
      CHUNK_IMAGE_FULL=$(echo "${TF_JSON}" | jq -r '.chunk_image_full.value // empty')
      IMAGE_TAG="${SHORT_SHA:-}"
      REPO="${_REPO:-}"
      ARTIFACT_REG_HOST="${_ARTIFACT_REG_HOST:-}"
      if [ -z "${CHUNK_IMAGE_FULL}" ] && [ -n "${ARTIFACT_REG_HOST}" ] && [ -n "${TF_PROJECT_ID}" ] && [ -n "${REPO}" ] && [ -n "${IMAGE_TAG}" ]; then
        CHUNK_IMAGE_FULL="${ARTIFACT_REG_HOST}/${TF_PROJECT_ID}/${REPO}/chunk-image:${IMAGE_TAG}"
      fi
      GITLAB_TOKEN="${GITLAB}"
      if [ -z "${GITLAB_TOKEN}" ]; then echo "ERROR: Could not read GITLAB secret"; exit 1; fi
      API="https://gitlab.com/api/v4/projects/${_GITLAB_PROJ_ID}/trigger/pipeline"
      curl -s -X POST "${API}" \
      -F token="${GITLAB_TRIGGER_TOKEN}" \
      -F ref="${_GITLAB_REF:-main}" \
      -F "variables[IMAGE_TAG]=${IMAGE_TAG}" \
      -F "variables[REPO]=${REPO}" \
      -F "variables[ARTIFACT_REG_HOST]=${ARTIFACT_REG_HOST}" \
      -F "variables[CHUNK_IMAGE_FULL]=${CHUNK_IMAGE_FULL}" \
      -F "variables[EMBEDDING_ENDPOINT]=${EMBEDDING_ENDPOINT}" \
      -F "variables[CHUNK_URL]=${CHUNK_URL}" \
      -F "variables[VECTOR_DB_ENDPOINT]=${VECTOR_DB_ENDPOINT}" \
      -F "variables[DEPLOYED_INDEX_ID]=${DEPLOYED_INDEX_ID}" \
      -F "variables[PROJECT_ID]=${TF_PROJECT_ID}" \
      -F "variables[REGION]=${TF_REGION}" \
      -F "variables[RUN_DEPLOY_TO_OSD]=true" \
      -o /workspace/gitlab_trigger_response.txt

images:
- '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:$SHORT_SHA'
- '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:$SHORT_SHA'
- '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:$SHORT_SHA'
- '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:$SHORT_SHA'
- '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:$SHORT_SHA'
