logsBucket: gs://${_PROJECT_ID}-build-logs    

steps:
# Build & push admin backend
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-admin-backend'
  args: ['build', '-t', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:$SHORT_SHA', './Admin_Backend']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-admin-backend'
  args: ['push', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:$SHORT_SHA']

# Build & push user backend (use singular 'user-backend')
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-user-backend'
  args: ['build', '-t', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:$SHORT_SHA', './Users_Backend']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-user-backend'
  args: ['push', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:$SHORT_SHA']

# Build & push chunk image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-chunk'
  args: ['build', '-t', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:$SHORT_SHA', './Chunk_Function']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-chunk'
  args: ['push', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:$SHORT_SHA']

# Build & push admin frontend
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-admin-frontend'
  args: ['build', '-t', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:$SHORT_SHA', './Admin_Frontend']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-admin-frontend'
  args: ['push', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:$SHORT_SHA']

# Build & push user frontend
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-user-frontend'
  args: ['build', '-t', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:$SHORT_SHA', './User_Frontend']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-user-frontend'
  args: ['push', '${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:$SHORT_SHA']

# # Trigger GitLab CI/CD (CD) via Pipeline Trigger
# - name: 'curlimages/curl'
#   id: 'trigger-gitlab'
#   entrypoint: 'sh'
#   secretEnv: ['GITLAB_TRIGGER_TOKEN']
#   args:
#     - '-c'
#     - |
#       echo "Triggering GitLab pipeline..."
#       API="https://gitlab.com/api/v4/projects/${_GITLAB_PROJ_ID}/trigger/pipeline"
#       curl -X POST \
#         -F token="$GITLAB_TRIGGER_TOKEN" \
#         -F ref="${_GITLAB_REF}" \
#         -F "variables[IMAGE_TAG]=$SHORT_SHA" \
#         -F "variables[ARTIFACT_HOST]=${_ARTIFACT_REG_HOST}" \
#         -F "variables[REPO]=${_REPO}" \
#         $API

# images:
# - "${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-backend:$SHORT_SHA"
# - "${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-backend:$SHORT_SHA"
# - "${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/chunk-image:$SHORT_SHA"
# - "${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/admin-frontend:$SHORT_SHA"
# - "${_ARTIFACT_REG_HOST}/${_PROJECT_ID}/${_REPO}/user-frontend:$SHORT_SHA"

# availableSecrets:
#   secretManager:
#   - versionName: "projects/YOUR_GCP_PROJECT/secrets/gitlab-trigger-token/versions/latest"
#     env: "GITLAB_TRIGGER_TOKEN"
